#!/bin/bash
# Usage: ./000-install-dependencies

# Extract installed bundles; append space to the end of each line.
installed_bundles=`swupd bundle-list | grep '^ - ' | sed 's/$/ /g'`

add_list=""
count=0

for bundle_name in \
    c-basic dev-utils nasm yasm sysadmin-basic devpkg-alsa-lib    \
    devpkg-appstream-glib devpkg-bzip2 devpkg-fontconfig          \
    devpkg-fribidi devpkg-freetype devpkg-gnutls devpkg-libass    \
    devpkg-libdrm devpkg-libgcrypt devpkg-libjpeg-turbo           \
    devpkg-libogg devpkg-librsvg devpkg-libtheora devpkg-libva    \
    devpkg-libvorbis devpkg-libvpx devpkg-libwebp devpkg-libX11   \
    devpkg-libxcb devpkg-libxml2 devpkg-libXvMC devpkg-mediasdk   \
    devpkg-mesa devpkg-numactl devpkg-opus devpkg-pulseaudio      \
    devpkg-SDL2 devpkg-SDL2_gfx devpkg-SDL2_image devpkg-SDL2_net \
    devpkg-SDL2_ttf devpkg-speex devpkg-v4l-utils devpkg-zlib     \
;do
    if [[ ! ${installed_bundles} =~ " - ${bundle_name} " ]]; then
        add_list="${add_list} ${bundle_name}"
    else
        count=$(( ${count} + 1 ))
    fi
done

# Add bundle for building the NVIDIA NVDEC-enabled VA-API driver.
if [[ -f /opt/nvidia/bin/nvidia-settings ]]; then
    if [[ ! ${installed_bundles} =~ " - devpkg-gst-plugins-bad " ]]; then
        add_list="${add_list} devpkg-gst-plugins-bad"
    else
        count=$(( ${count} + 1 ))
    fi
fi

# Buidling FFmpeg with flags "--enable-vulkan --enable-libglslang"
# requires glslang and vulkan header files provided by developer-gpu.
# Add bundle optionally due to missing glslang headers in CL <= 35920.
if [[ ! ${installed_bundles} =~ " - developer-gpu " ]]; then
    osrel=$( grep VERSION_ID /etc/os-release | cut -f2 -d= )
    [[ $osrel -ge 35730 ]] && add_list="${add_list} developer-gpu"
else
    count=$(( ${count} + 1 ))
fi

if [[ -n ${add_list} ]]; then
    add_list=${add_list## } # remove leading whitespace
    echo "swupd bundle-add ${add_list}"
    swupd bundle-add ${add_list}
fi

if [[ ${count} -gt 0 ]]; then
    echo "${count} bundles were already installed"
fi

