#!/bin/bash

# Exit silently if the graphics driver is not installed.
[[ ! -f /opt/nvidia/bin/nvidia-settings ]] && exit 0

echo "building nv-codec-headers"

version=`/opt/nvidia/bin/nvidia-settings --version | grep version`
version=${version##* } # extract the version string from the line
version=`echo $version | cut -d. -f1-2` # want major and minor, not revision

if [[ $(bc -l <<< "${version} < 470.57") -eq 1 ]]; then
    echo "Warning: NVIDIA graphics driver is older than 470.57, skipping build..."
    exit 0
fi

nvver="11.1.5.1"
echo "building nv-codec-headers"

mkdir -p builddir && cd builddir
rm -fr "nv-codec-headers-${nvver}"

if [[ ! -f nv-codec-headers-${nvver}.tar.gz ]]; then
    url="https://github.com/FFmpeg/nv-codec-headers/releases/download/n${nvver}/nv-codec-headers-${nvver}.tar.gz"
    echo "curl -LO ${url}"
    curl -LO ${url}
fi

tar xzf nv-codec-headers-${nvver}.tar.gz

if [[ -d nv-codec-headers-${nvver} ]]; then
    cd nv-codec-headers-${nvver}
    make PREFIX=/usr/local && \
    make install
fi

