#!/bin/bash

name="x265"
version="3.5"
echo "building ${name}_${version}"

mkdir -p builddir && cd builddir
rm -fr ${name}_${version}

if [[ ! -f ${name}_${version}.tar.gz ]]; then
    url="https://bitbucket.org/multicoreware/x265_git/downloads/${name}_${version}.tar.gz"
    echo "curl -LO ${url}"
    curl -LO ${url}
fi

tar xzf ${name}_${version}.tar.gz

if [[ -d ${name}_${version} ]]; then
    cores=`grep -c '^cpu[0-9]' /proc/stat`
    cd ${name}_${version}

    # Fix for ENABLE_PIC.
    sed -i 's/-fPIC/-fPIC -DPIC/' source/CMakeLists.txt

    # Multilib support; copy api.cpp, restored later.
    cp source/encoder/api.cpp source/encoder/api.cpp.orig
    patch -p0 < ../../patches/x265-high-bit-depth-soname.patch || exit $?

    echo "Building the ${name} 12-bit shared library..."
    mkdir -p 12bit && cd 12bit

    cmake -Wno-dev -G Ninja -DCMAKE_POSITION_INDEPENDENT_CODE=1 \
        -DCMAKE_SKIP_RPATH:BOOL=YES -DCMAKE_INSTALL_PREFIX=/usr/local \
        -DENABLE_SHARED=1 -DENABLE_PIC:BOOL=1 -DCMAKE_BUILD_TYPE=Release \
        -DENABLE_CLI=0 -DHIGH_BIT_DEPTH=1 -DMAIN12=1 ../source && \
    ninja || exit $?
    ninja install || exit $?

    echo "Building the ${name} 10-bit shared library..."
    cd .. && mkdir -p 10bit && cd 10bit

    cmake -Wno-dev -G Ninja -DCMAKE_POSITION_INDEPENDENT_CODE=1 \
        -DCMAKE_SKIP_RPATH:BOOL=YES -DCMAKE_INSTALL_PREFIX=/usr/local \
        -DENABLE_SHARED=1 -DENABLE_PIC:BOOL=1 -DCMAKE_BUILD_TYPE=Release \
        -DENABLE_CLI=0 -DHIGH_BIT_DEPTH=1 ../source && \
    ninja || exit $?
    ninja install || exit $?

    echo "Building the ${name} 8-bit shared library and cli tools..."
    cd .. && mkdir -p 8bit && cd 8bit

    # Restore api.cpp for the 8-bit build.
    cp ../source/encoder/api.cpp.orig ../source/encoder/api.cpp

    cmake -Wno-dev -G Ninja -DCMAKE_POSITION_INDEPENDENT_CODE=1 \
        -DCMAKE_SKIP_RPATH:BOOL=YES -DCMAKE_INSTALL_PREFIX=/usr/local \
        -DENABLE_SHARED=1 -DENABLE_PIC:BOOL=1 -DCMAKE_BUILD_TYPE=Release \
        -DENABLE_HDR10_PLUS=YES ../source && \
    ninja && ninja install && \
    rm -f /usr/local/lib/libhdr10plus.a /usr/local/lib/libx265.a
fi

